# Generated by Django 3.1.7 on 2021-04-30 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_apartments_bill_complaint_section_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='apartment_id',
        ),
        migrations.AddField(
            model_name='apartments',
            name='owner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.user'),
        ),
    ]
