# Generated by Django 3.1.7 on 2021-04-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_auto_20210430_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='price',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
