# Generated by Django 3.1.7 on 2021-04-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_apartments_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='img',
            field=models.CharField(default='NULL', max_length=1000),
        ),
        migrations.AlterField(
            model_name='apartments',
            name='flat_number',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
